### ISSUE TITLE
download boot get an error!!

### ISSUE THREAD

**Issue by 54shady** [rockchip-linux/rkdeveloptool#13]
Need help. Get an error when I do the command as below(already in the rockusb download mode, try mask rom mode too)

./rkdeveloptool db rk3399_loader_v1.08.106.bin

The device does not support this operation!

**Comment by eddiecailinux** [comment]
your device have to enter maskrom mode when you are using db command. 
http://rockchip.wikidot.com/how-to-enter-rockusb-maskrom-mode

**Comment by 54shady** [comment]
I do as the "how to enter rockusb maskrom mode" but the device was found as a "loader device",(the device is in loader mode)
and I  erase the flash or upgrade with update.img in this strang loader mode will cause the result for "prepare idb faild"

so strange ......

**Comment by 54shady** [comment]
oops...Enter the maskrom mode, but i do nothing, it just ok now...
