### ISSUE TITLE
Question about the default partition map

### ISSUE THREAD

**Issue by 54shady** [rockchip-linux/rkdeveloptool#14]
As the wiki page show the default partition map, the first one sector is MBR? and GPT is start with second sector
 
http://opensource.rock-chips.com/wiki_Partitions

I use upgade_tool to read LBA begin sector 0, the result is below, which is equal to my parameter's context

Rockusb>rl 0 1
00000000 50 41 52 4D 62 02 00 00 46 49 52 4D 57 41 52 45      PARMb...FIRMWARE
00000001 5F 56 45 52 3A 20 36 2E 30 2E 31 0A 4D 41 43 48      _VER: 6.0.1.MACH
00000002 49 4E 45 5F 4D 4F 44 45 4C 3A 20 52 4B 33 33 39      INE_MODEL: RK339
00000003 39 0A 4D 41 43 48 49 4E 45 5F 49 44 3A 20 30 30      9.MACHINE_ID: 00
00000004 37 0A 4D 41 4E 55 46 41 43 54 55 52 45 52 3A 20      7.MANUFACTURER: 

I use rkflashtool to read from lba0 2sector

rkflashtool r 0x0 2 > paramter.txt    ===> which is equal to my local parame.txt

As you can see the first is not the MBR, but the GPT

Am I get somethig worng? I am confused....

**Comment by 54shady** [comment]
the charcter  "PARMb " is a must ? what's tha' support to mean?

**Comment by 54shady** [comment]
oops.. I got it, the PARM is a hard code tag....

**Comment by 54shady** [comment]
But the question raise in the comment 1 is still exist. GPT is store in the LBA0...? am I right?? hope you can give me a direction or point me out.

**Comment by eddiecailinux** [comment]
https://en.wikipedia.org/wiki/GUID_Partition_Table
