### ISSUE TITLE
autoconf failed in XUbuntu 16.04.03 desktop

### ISSUE THREAD

**Issue by CodyXie** [rockchip-linux/rkdeveloptool#18]
<pre>
autoconf -i
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:8: error: possibly undefined macro: AM_CONFIG_HEADER
</pre>
Fixed following by :
https://bugs.freedesktop.org/show_bug.cgi?id=87297
___
### Please add the following  to README.md
<pre>
sudo apt install pkg-config libtool-bin
libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
</pre>
Then
<pre>
./configure
make
</pre>

**Comment by wzyy2** [comment]
I think `autoreconf -i` will run things in the right order.
https://github.com/rockchip-linux/rkdeveloptool/blob/master/Readme.txt#L7

**Comment by CodyXie** [comment]
......
