### ISSUE TITLE
load ubootloader succeeded, but still cannot flash data into emmc

### ISSUE THREAD

**Issue by sprhawk** [rockchip-linux/rkdeveloptool#20]
I use RK3288 chip

under ubuntu 16.04

```
sudo ./rkdeveloptool db rk3288_ubootloader.bin
```
 it showed "Downloading bootloader succeeded.", but still failed to use wl command "Did not find any rockusb device, please plug device in!", or it will hang and no responding

But I can flash image with Android Tool (RKDevTool 2.39) without problem (with same boot loader)

**Comment by sprhawk** [comment]
I found the reason.

I was using a Virtual machine (Virtualbox)  to operate the device. When I changed to use a physical computer with a Linux to try again, it works

**Comment by zigguratt** [comment]
@sprhawk That's not necessarily the reason. I've compiled the `rkdeveloptool` utility on Darwin and it exhibits the same problems as your VM-hosted utility. The problem may be that despite being able to run the utility on macOS or on Linux(?) in a VMs, it may not function properly on anything but a full Linux computer.

It also fails to erase the eMMC, giving similar errors:

```
$ rkdeveloptool ef
Did not find any rockusb device, please plug device in!
$ rkdeveloptool ef
Starting to erase flash...
Getting flash info from device failed!
```

**Comment by battosai30** [comment]
Hi, 

Just in case someone met the same error : it's possible with virtual box, you just have to allow the USB Device all the time going under USB parameter and adding it. Just connect it from the drop down USB menu is not enough.

Bye

**Comment by diecalsa** [comment]
Hi @battosai30,

I am facing this exact problem, could you please explain how to allow the USB Device all the time going under USB parameter and adding it?. 

Thanks in advance!

**Comment by cutec-chris** [comment]
from where can i get the rk3288_ubootloader.bin ?
