### ISSUE TITLE
Can(or would) this tool support downloading uboot in the loader mode?

### ISSUE THREAD

**Issue by alanlilyan** [rockchip-linux/rkdeveloptool#22]
In my Firefly rk3288 development board, it's hard to get into the maskrom mode. So when I execute the command as `rkdeveloptool db uboot.bin`, I would get the error like "the device doesn't support this operation.". I read the source code and find that it can only execute function `download_boot()` and `upgrade_loader()` successfully in maskrom mode，but the `upgrade_tool` or other tools don't have the problem.
 
1. I want to that could this tool support in loader mode (booting with pressed recovery key) to download the uboot.bin?
2. What's the difference in these two modes, loader mode, and maskrom mode?  It looks like the download happening after or before loading u-boot.

**Comment by wzyy2** [comment]
You can find the answer in the below links.

http://opensource.rock-chips.com/wiki_Boot_option
http://opensource.rock-chips.com/wiki_Rockusb
