### ISSUE TITLE
Flashing a NanoPI M4

### ISSUE THREAD

**Issue by landersson** [rockchip-linux/rkdeveloptool#33]
I'm trying to use this tool to update the kernel image on a NanoPI M4 (RK 3399). I can enter maskrom mode by pulling out the eMMC card, and the device is detected by rkdeveloptool:
```
kdeveloptool:>./rkdeveloptool ld
DevNo=1	Vid=0x2207,Pid=0x330c,LocationID=102	Maskrom
```

All other commands seem to fail though:
```
./rkdeveloptool rd 3
Reset Device failed!

./rkdeveloptool rl 0xe000 1000 out.bin
Read LBA failed!
```
Any idea why this isn't working?

**Comment by landersson** [comment]
Entering maskrom mode via the "rockusb" command rather than by pulling out the eMMC card fixes the problem for me.

**Comment by monitorjbl** [comment]
Ran into this myself and figured I'd share my solution. You have to flash the bootloader *first* using the `rkdeveloptool db` command. This will initialize the device and prepare it to accept a disk image when you use the `rkdeveloptool wl` command. If you don't do things in this exact order, you'll get the `Write LBA failed!` error. Not obvious or intuitive, but embedded tools rarely are!

My boards are NanoPi R5S, so I had to grab the bootloader from their site. Unfortunately, it doesn't appear to be opensource, and you have to download from a sketchy Google Drive link. I think every vendor is probably slightly different though, so not sure that this bootloader will work for just any board.

If you're in my _exact_ position, the bootloader was in the `01_Official images/03_USB Upgrade images/rk3568-usb-friendlywrt-23.05-20241112.zip` archive and it was named `MiniLoaderAll.bin`. I got that that link from the FriendlyElec wiki: https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R5S#Tools_.28optional.29.
