### ISSUE TITLE
Can this tool support sdram read write and execute operation?

### ISSUE THREAD

**Issue by 54shady** [rockchip-linux/rkdeveloptool#9]
can this tool support sdram read write and execute operation?

such as below operations:

rkdeveloptool read sdram_addr len  // read file from sdram
rkdeveloptool write sdram_addr  file // download file to sdram address
rkdeveloptool execute sdram_addr // execute the instruction

**Comment by keveryang** [comment]
No, it does not support, why do you need this feature? you can read the sdram memory by the md command in U-Boot.
